### ISSUE TITLE
编译不成功，劳烦大神赐教

### ISSUE THREAD

**Issue by DellDuckDuck** [ilovexjp/healthcode-backup#1]
我用28编译，显示错误：
      A problem occurred configuring project ':app'.
           > java.lang.NullPointerException (no error message)
是不是我build tool 版本不对，大神您有没有邮箱啊，跟您请教一下

**Comment by ilovexjp** [comment]
原作者不是我，可以去原repo里看看。我这里只留存了一个编译过的版本备份。
