### ISSUE TITLE
bjjkb 扫码后提示音不是《通过>，是《绿码，核酸一天》

### ISSUE THREAD

**Issue by slon2000** [ilovexjp/healthcode-backup#13]
为啥用演示网址可以进扫码，听到提示音，自己部署到网站，扫码那页就没动静，也没提示音，只能跳过扫码才能进下一页

**Comment by ilovexjp** [comment]
提示音已经更正，稍后会更新源码。

自己部署的话可能需要在 https 下才能调用摄像头。
