### ISSUE TITLE
您好，请问行程码的包可以发一下吗

### ISSUE THREAD

**Issue by lzy888777** [ilovexjp/healthcode-backup#3]

**Comment by ilovexjp** [comment]
放到Release里了

**Comment by lzy888777** [comment]
谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月10日(星期四) 晚上10:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ilovexjp/healthcode-backup] 您好，请问行程码的包可以发一下吗 (Issue #3)





 
放到Release里了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
