### ISSUE TITLE
大老，能否做个月康马？？？

### ISSUE THREAD

**Issue by yyked** [ilovexjp/healthcode-backup#8]
大老，能否做个月康马？？？

**Comment by ilovexjp** [comment]
可以试试 https://ykm.pages.dev/

**Comment by yyked** [comment]
> 可以试试 https://ykm.pages.dev/

太强太劲了，大佬，非常感谢，但是请问有没国内能直连的链接，好像国内上不了，不知道有没防和谐的链接？

**Comment by ilovexjp** [comment]
> > 可以试试 https://ykm.pages.dev/
> 
> 太强太劲了，大佬，非常感谢，但是请问有没国内能直连的链接，好像国内上不了，不知道有没防和谐的链接？

这个链接国内应该是可以上的，不行的话也可以用 Netlify 的链接或者去 repo 下载源码自行部署。
