### ISSUE TITLE
北京健康宝，现在样式变了，您原贴里这个已经不能用了，能整个更新不？：）多谢多谢

### ISSUE THREAD

**Issue by slon2000** [ilovexjp/healthcode-backup#9]

**Comment by ilovexjp** [comment]
可以试试 https://github.com/ilovexjp/jkb-simulator

**Comment by slon2000** [comment]
> 可以试试 https://github.com/ilovexjp/jkb-simulator

多谢，收到，最好把进各种场所门口扫码完给二狗子们看的那界面一并弄了，这样就全套齐活
